In [1]:
import pandas as pd
import numpy as np

from sklearn import preprocessing
from sklearn.preprocessing import (StandardScaler, OrdinalEncoder,LabelEncoder, MinMaxScaler, OneHotEncoder, LabelBinarizer)

# Dataset Analysis

In [11]:
train = pd.read_csv('/home/faraz/PycharmProjects/IDS/dataset/UNSW_NB15/file/original/UNSW_NB15_training-set.csv')
test = pd.read_csv('/home/faraz/PycharmProjects/IDS/dataset/UNSW_NB15/file/original/UNSW_NB15_testing-set.csv')

In [13]:
train.drop(labels= 'id', axis= 1, inplace= True)
test.drop(labels= 'id', axis= 1, inplace= True)

In [14]:
train

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.000011,udp,-,INT,2,0,496,0,90909.090200,254,...,1,2,0,0,0,1,2,0,Normal,0
1,0.000008,udp,-,INT,2,0,1762,0,125000.000300,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000005,udp,-,INT,2,0,1068,0,200000.005100,254,...,1,3,0,0,0,1,3,0,Normal,0
3,0.000006,udp,-,INT,2,0,900,0,166666.660800,254,...,1,3,0,0,0,2,3,0,Normal,0
4,0.000010,udp,-,INT,2,0,2126,0,100000.002500,254,...,1,3,0,0,0,2,3,0,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82327,0.000005,udp,-,INT,2,0,104,0,200000.005100,254,...,1,2,0,0,0,2,1,0,Normal,0
82328,1.106101,tcp,-,FIN,20,8,18062,354,24.410067,254,...,1,1,0,0,0,3,2,0,Normal,0
82329,0.000000,arp,-,INT,1,0,46,0,0.000000,0,...,1,1,0,0,0,1,1,1,Normal,0
82330,0.000000,arp,-,INT,1,0,46,0,0.000000,0,...,1,1,0,0,0,1,1,1,Normal,0
82331,0.000009,udp,-,INT,2,0,104,0,111111.107200,254,...,1,1,0,0,0,1,1,0,Normal,0

In [15]:
test

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.121478,tcp,-,FIN,6,4,258,172,74.087490,252,...,1,1,0,0,0,1,1,0,Normal,0
1,0.649902,tcp,-,FIN,14,38,734,42014,78.473372,62,...,1,2,0,0,0,1,6,0,Normal,0
2,1.623129,tcp,-,FIN,8,16,364,13186,14.170161,62,...,1,3,0,0,0,2,6,0,Normal,0
3,1.681642,tcp,ftp,FIN,12,12,628,770,13.677108,62,...,1,3,1,1,0,2,1,0,Normal,0
4,0.449454,tcp,-,FIN,10,6,534,268,33.373826,254,...,1,40,0,0,0,2,39,0,Normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175336,0.000009,udp,dns,INT,2,0,114,0,111111.107200,254,...,13,24,0,0,0,24,24,0,Generic,1
175337,0.505762,tcp,-,FIN,10,8,620,354,33.612649,254,...,1,2,0,0,0,1,1,0,Shellcode,1
175338,0.000009,udp,dns,INT,2,0,114,0,111111.107200,254,...,3,13,0,0,0,3,12,0,Generic,1
175339,0.000009,udp,dns,INT,2,0,114,0,111111.107200,254,...,14,30,0,0,0,30,30,0,Generic,1
175340,0.000009,udp,dns,INT,2,0,114,0,111111.107200,254,...,16,30,0,0,0,30,30,0,Generic,1

In [16]:
train.columns

Index(['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes',
       'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss',
       'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin',
       'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth',
       'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm',
       'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm',
       'ct_srv_dst', 'is_sm_ips_ports', 'attack_cat', 'label'],
      dtype='object')

In [7]:
train.dtypes

dur                  float64
proto                 object
service               object
state                 object
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object

In [8]:
for col in train.columns:
    if len(train[col].unique()) < 20 or train[col].dtype == 'object':
        print(col, ' ', train[col].unique())
    else:
        print(col, ' ', len(train[col].unique()))
    print('-------------------------------------')

dur   39888
-------------------------------------
proto   ['udp' 'arp' 'tcp' 'igmp' 'ospf' 'sctp' 'gre' 'ggp' 'ip' 'ipnip' 'st2'
 'argus' 'chaos' 'egp' 'emcon' 'nvp' 'pup' 'xnet' 'mux' 'dcn' 'hmp' 'prm'
 'trunk-1' 'trunk-2' 'xns-idp' 'leaf-1' 'leaf-2' 'irtp' 'rdp' 'netblt'
 'mfe-nsp' 'merit-inp' '3pc' 'idpr' 'ddp' 'idpr-cmtp' 'tp++' 'ipv6' 'sdrp'
 'ipv6-frag' 'ipv6-route' 'idrp' 'mhrp' 'i-nlsp' 'rvd' 'mobile' 'narp'
 'skip' 'tlsp' 'ipv6-no' 'any' 'ipv6-opts' 'cftp' 'sat-expak' 'ippc'
 'kryptolan' 'sat-mon' 'cpnx' 'wsn' 'pvp' 'br-sat-mon' 'sun-nd' 'wb-mon'
 'vmtp' 'ttp' 'vines' 'nsfnet-igp' 'dgp' 'eigrp' 'tcf' 'sprite-rpc' 'larp'
 'mtp' 'ax.25' 'ipip' 'aes-sp3-d' 'micp' 'encap' 'pri-enc' 'gmtp' 'ifmp'
 'pnni' 'qnx' 'scps' 'cbt' 'bbn-rcc' 'igp' 'bna' 'swipe' 'visa' 'ipcv'
 'cphb' 'iso-tp4' 'wb-expak' 'sep' 'secure-vmtp' 'xtp' 'il' 'rsvp' 'unas'
 'fc' 'iso-ip' 'etherip' 'pim' 'aris' 'a/n' 'ipcomp' 'snp' 'compaq-peer'
 'ipx-n-ip' 'pgm' 'vrrp' 'l2tp' 'zero' 'ddx' 'iatp' 'stp' 'srp' 'uti' 'sm'
 'smp' 'isis' 'ptp' 'fire' 'crtp' 'crudp' 'sccopmce' 'iplt' 'pipe' 'sps'
 'ib']
-------------------------------------
service   ['-' 'http' 'ftp' 'ftp-data' 'smtp' 'pop3' 'dns' 'snmp' 'ssl' 'dhcp' 'irc'
 'radius' 'ssh']
-------------------------------------
state   ['INT' 'FIN' 'REQ' 'ACC' 'CON' 'RST' 'CLO']
-------------------------------------
spkts   420
-------------------------------------
dpkts   436
-------------------------------------
sbytes   4489
-------------------------------------
dbytes   4034
-------------------------------------
rate   40616
-------------------------------------
sttl   [254   0  62 255  31  60   1  32  29  30  63]
-------------------------------------
dttl   [  0 252  60  29  31  30  32 253]
-------------------------------------
sload   42873
-------------------------------------
dload   40614
-------------------------------------
sloss   253
-------------------------------------
dloss   311
-------------------------------------
sinpkt   39970
-------------------------------------
dinpkt   37617
-------------------------------------
sjit   39944
-------------------------------------
djit   38381
-------------------------------------
swin   [  0 255 156 202  99   5  67 154  52 245  43]
-------------------------------------
stcpb   39219
-------------------------------------
dtcpb   39108
-------------------------------------
dwin   [  0 255  81 160  77 171 137 164  27  33 209  12  46 125]
-------------------------------------
tcprtt   26130
-------------------------------------
synack   24934
-------------------------------------
ackdat   24020
-------------------------------------
smean   1282
-------------------------------------
dmean   1222
-------------------------------------
trans_depth   [  0   1 131   2   9   3   4   8]
-------------------------------------
response_body_len   1190
-------------------------------------
ct_srv_src   57
-------------------------------------
ct_state_ttl   [2 1 6 4 0 3 5]
-------------------------------------
ct_dst_ltm   50
-------------------------------------
ct_src_dport_ltm   50
-------------------------------------
ct_dst_sport_ltm   33
-------------------------------------
ct_dst_src_ltm   57
-------------------------------------
is_ftp_login   [0 1 2]
-------------------------------------
ct_ftp_cmd   [0 1 2]
-------------------------------------
ct_flw_http_mthd   [ 0  1  9  4  2 16 12  6]
-------------------------------------
ct_src_ltm   50
-------------------------------------
ct_srv_dst   57
-------------------------------------
is_sm_ips_ports   [0 1]
-------------------------------------
attack_cat   ['Normal' 'Reconnaissance' 'Backdoor' 'DoS' 'Exploits' 'Analysis'
 'Fuzzers' 'Worms' 'Shellcode' 'Generic']
-------------------------------------
label   [0 1]
-------------------------------------

In [10]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 44 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   dur                175341 non-null  float64
 1   proto              175341 non-null  object
 2   service            175341 non-null  object
 3   state              175341 non-null  object
 4   spkts              175341 non-null  int64
 5   dpkts              175341 non-null  int64
 6   sbytes             175341 non-null  int64
 7   dbytes             175341 non-null  int64
 8   rate               175341 non-null  float64
 9   sttl               175341 non-null  int64
 10  dttl               175341 non-null  int64
 11  sload              175341 non-null  float64
 12  dload              175341 non-null  float64
 13  sloss              175341 non-null  int64
 14  dloss              175341 non-null  int64
 15  sinpkt             175341 non-null  float64
 16  dinpkt             175341 non-null  float64
 17  sjit               175341 non-null  float64
 18  djit               175341 non-null  float64
 19  swin               175341 non-null  int64
 20  stcpb              175341 non-null  int64
 21  dtcpb              175341 non-null  int64
 22  dwin               175341 non-null  int64
 23  tcprtt             175341 non-null  float64
 24  synack             175341 non-null  float64
 25  ackdat             175341 non-null  float64
 26  smean              175341 non-null  int64
 27  dmean              175341 non-null  int64
 28  trans_depth        175341 non-null  int64
 29  response_body_len  175341 non-null  int64
 30  ct_srv_src         175341 non-null  int64
 31  ct_state_ttl       175341 non-null  int64
 32  ct_dst_ltm         175341 non-null  int64
 33  ct_src_dport_ltm   175341 non-null  int64
 34  ct_dst_sport_ltm   175341 non-null  int64
 35  ct_dst_src_ltm     175341 non-null  int64
 36  is_ftp_login       175341 non-null  int64
 37  ct_ftp_cmd         175341 non-null  int64
 38  ct_flw_http_mthd   175341 non-null  int64
 39  ct_src_ltm         175341 non-null  int64
 40  ct_srv_dst         175341 non-null  int64
 41  is_sm_ips_ports    175341 non-null  int64
 42  attack_cat         175341 non-null  object
 43  label              175341 non-null  int64
dtypes: float64(11), int64(29), object(4)
memory usage: 58.9+ MB

In [223]:
for col in train.columns:
    if (train[col].dtype == 'object') and (col != 'attack_cat'):
        freq = train[col].value_counts()
        print(col, ':', '\n', freq)

proto :
 tcp           43095
udp           29418
unas           3515
arp             987
ospf            676
              ...
br-sat-mon       32
pvp              32
wsn              32
ib               31
igmp             30
Name: proto, Length: 131, dtype: int64
service :
 -           47153
dns         21367
http         8287
smtp         1851
ftp          1552
ftp-data     1396
pop3          423
ssh           204
ssl            30
snmp           29
dhcp           26
radius          9
irc             5
Name: service, dtype: int64
state :
 FIN    39339
INT    34163
CON     6982
REQ     1842
ACC        4
RST        1
CLO        1
Name: state, dtype: int64

In [239]:
services_frequency = train['proto'].value_counts()
#subsetServices= list(services_frequency[:].index)
services_frequency['a/n']

32

# Dataset Prepration

In [242]:
class BuildDataFrames: 
    
    def __init__(self, dataFrame_path, DataFrame_type): #, augmentation, oversample_method
        
        self.dataFrame_path = dataFrame_path
        self.DataFrame_type = DataFrame_type
        #self.augmentation = augmentation
        #self.ReadDataFrames()
  
    def ReadDataFrames(self):
        
        self.DataFrame = pd.read_csv(self.dataFrame_path)
        self.DataFrame.drop(['id', 'label'], axis=1, inplace=True)
        return self.DataFrame
    
    def Normalization(self, min_max_scaler_obj = None):
        
        if (self.DataFrame_type == 'train'):
            DataFrame = self.DataFrame
            numeric_col_list = DataFrame.select_dtypes(include='number').columns
            DataFrame_numeric_col = DataFrame[numeric_col_list].values
            min_max_scaler = preprocessing.MinMaxScaler()
            DataFrame_numeric_col_scaled = min_max_scaler.fit_transform(DataFrame_numeric_col)
            DataFrame_numeric_col_scaled = pd.DataFrame(DataFrame_numeric_col_scaled, columns= numeric_col_list)
            self.DataFrame[numeric_col_list] = DataFrame_numeric_col_scaled
            return self.DataFrame, min_max_scaler
        elif (self.DataFrame_type == 'test'):
            DataFrame = self.DataFrame
            numeric_col_list = DataFrame.select_dtypes(include='number').columns
            DataFrame_numeric_col = DataFrame[numeric_col_list].values
            DataFrame_numeric_col_scaled = min_max_scaler_obj.transform(DataFrame_numeric_col)
            DataFrame_numeric_col_scaled = pd.DataFrame(DataFrame_numeric_col_scaled, columns= numeric_col_list)
            self.DataFrame[numeric_col_list] = DataFrame_numeric_col_scaled
            return self.DataFrame
        
    def OneHotEncoding(self, label_feature_name): # label_feature_name for UNSW-NB15 is 'label' for binary classification and 'attack_cat' for multi classification
        
        categorical_column_list = list(self.DataFrame.select_dtypes(include='object').columns)
        categorical_column_list.remove(label_feature_name)
  
        one_hot_DataFrame = pd.get_dummies(self.DataFrame, columns=categorical_column_list)
        one_hot_DataFrame_cols = one_hot_DataFrame.columns
        
        train_label_col = one_hot_DataFrame.pop(label_feature_name)
        one_hot_DataFrame.insert(len(one_hot_DataFrame.columns), label_feature_name, train_label_col) #position parameter for insert function starts with 0 so we dont need to len(one_hot_train.columns)+1 (after pop function)

        self.DataFrame = one_hot_DataFrame

        return self.DataFrame, one_hot_DataFrame_cols
    
    def RescalingBetweenTrainTest(self, train_one_hot_cols, test_one_hot_cols):
        
        if self.DataFrame_type == 'train':
            diff_test_train = list(set(test_one_hot_cols) - set(train_one_hot_cols))
            if len(diff_test_train)>0 :
                zero_values = [0] * len(self.DataFrame)
                for col in diff_test_train:
                    self.DataFrame[col] = zero_values
                    
                #upcoming 2 lines of code, take attack_cat column and put it at the last column
                train_label_col = self.DataFrame.pop('attack_cat')
                self.DataFrame.insert(len(self.DataFrame.columns), 'attack_cat', train_label_col)
                return self.DataFrame
            else:
                return self.DataFrame
        
        elif self.DataFrame_type == 'test':
            diff_train_test = list(set(train_one_hot_cols) - set(test_one_hot_cols))
            if len(diff_train_test)>0 :
                zero_values = [0] * len(self.DataFrame)
                for col in diff_train_test:
                    self.DataFrame[col] = zero_values
                
                #upcoming 2 lines of code, take attack_cat column and put it at the last column
                test_label_col = self.DataFrame.pop('attack_cat')
                self.DataFrame.insert(len(self.DataFrame.columns), 'attack_cat', test_label_col)
                return self.DataFrame
            else:
                return self.DataFrame

    def LabelBinarize(self, LabelBinarizerObj = None):
        
        if self.DataFrame_type == 'train':     
            LabelBinarizerObject_fittedOnTrainLabel = LabelBinarizer().fit(self.DataFrame['attack_cat']) # create an object of label binarizer, then fit on train labels
            TrainBinarizedLabel = LabelBinarizerObject_fittedOnTrainLabel.transform(self.DataFrame['attack_cat']) # transform train labels with that object
            TrainBinarizedLabelDataFrame = pd.DataFrame(TrainBinarizedLabel, columns= LabelBinarizerObject_fittedOnTrainLabel.classes_) #convert transformed labels to dataframe
            self.DataFrame = pd.concat([self.DataFrame.drop(['attack_cat'], axis=1), TrainBinarizedLabelDataFrame],axis=1) # concatinate training set after drop 'label' with created dataframe of binarized labels
            return self.DataFrame, LabelBinarizerObject_fittedOnTrainLabel
        
        elif self.DataFrame_type == 'test':
            
            TestBinarizedLabel = LabelBinarizerObj.transform(self.DataFrame['attack_cat'])
            TestBinarizedLabelDataFrame = pd.DataFrame(TestBinarizedLabel, columns= LabelBinarizerObj.classes_)
            self.DataFrame = pd.concat([self.DataFrame.drop(['attack_cat'], axis=1), TestBinarizedLabelDataFrame],axis=1)
            return self.DataFrame

In [243]:
train_path= 'C:\\Users\\faraz\\Desktop\\UNSW-NB15 Dataset\\UNSW_NB15_training-set.csv'
test_path= 'C:\\Users\\faraz\\Desktop\\UNSW-NB15 Dataset\\UNSW_NB15_testing-set.csv'

In [244]:
preprocess_train = BuildDataFrames(dataFrame_path= train_path, DataFrame_type= 'train')
train = preprocess_train.ReadDataFrames()
train_normalized, min_max_scaler_obj = preprocess_train.Normalization()
train_one_hot, train_one_hot_cols = preprocess_train.OneHotEncoding('attack_cat')

In [245]:
preprocess_test = BuildDataFrames(dataFrame_path= test_path, DataFrame_type= 'test')
test = preprocess_test.ReadDataFrames()
test_normalized = preprocess_test.Normalization(min_max_scaler_obj= min_max_scaler_obj)
test_one_hot, test_one_hot_cols = preprocess_test.OneHotEncoding('attack_cat')

In [246]:
train_rescaled = preprocess_train.RescalingBetweenTrainTest(train_one_hot_cols= train_one_hot_cols, test_one_hot_cols= test_one_hot_cols)
test_rescaled = preprocess_test.RescalingBetweenTrainTest(train_one_hot_cols= train_one_hot_cols, test_one_hot_cols= test_one_hot_cols)

In [247]:
train_LabelBinerized, LabelBinerizerObj = preprocess_train.LabelBinarize()
test_LabelBinerized = preprocess_test.LabelBinarize(LabelBinarizerObj= LabelBinerizerObj)

In [ ]:
#check deference between train and test columns
'''
categorical_column_list = list(train.select_dtypes(include='object').columns)
categorical_column_list.remove('attack_cat')
print(categorical_column_list)
  
one_hot_train = pd.get_dummies(train, columns=categorical_column_list)
one_hot_test = pd.get_dummies(test, columns=categorical_column_list)

print('train columns:', len(one_hot_train.columns))
print('test columns:', len(one_hot_test.columns))

diff_test_train = len(set(one_hot_test.columns) - set(one_hot_train.columns))
diff_train_test = len(set(one_hot_train.columns) - set(one_hot_test.columns))
#diff = list(set(one_hot_test.columns) - set(one_hot_train.columns)) + list(set(one_hot_train.columns) - set(one_hot_test.columns))
print('difference between train and test that must be rescale:', diff_train_test)
print('difference between test and train that must be rescale:', diff_test_train)
'''

In [248]:
#checking (must get 2 empty lists)
diff_test_train = list(set(test_rescaled.columns) - set(train_rescaled.columns))
diff_train_test = list(set(train_rescaled.columns) - set(test_rescaled.columns))
diff_test_train, diff_train_test

([], [])

In [249]:
def SortColumnsBetweenTrainTest(train, test):
    train_cols = train.columns
    test_sortedBasedOnTrain = pd.DataFrame(columns= train_cols)
    for col in test_sortedBasedOnTrain:
        test_sortedBasedOnTrain[col] = test[col]
        
    return train, test_sortedBasedOnTrain

train_sorted, test_sorted = SortColumnsBetweenTrainTest(train_LabelBinerized, test_LabelBinerized)

In [285]:
def PictureFormat(DataFrame): # do PictureFormat after LabelBinarize and Sorting
    
    class_columns= DataFrame.iloc[:, -10:].columns

    X = DataFrame.drop(class_columns , axis=1)
    y = DataFrame[class_columns]

    X = np.array(X)
    y = np.array(y)
    print('Data has shape of:', np.shape(X), '\nLabel has shape of:' , np.shape(y))

    X= np.reshape(X, ( X.shape[0],  14,14,1))
    print('X shape is:', np.shape(X), '\ny shape is:' , np.shape(y))

    return X, y

X_train, y_train = PictureFormat(train_sorted)
print('=============')
X_test, y_test = PictureFormat(test_sorted)

Data has shape of: (82332, 196)
Label has shape of: (82332, 10)
X shape is: (82332, 14, 14, 1)
y shape is: (82332, 10)
=============
Data has shape of: (175341, 196)
Label has shape of: (175341, 10)
X shape is: (175341, 14, 14, 1)
y shape is: (175341, 10)

In [ ]:
'''
train_sorted.iloc[:, -10:] 
train_sorted.iloc[:, :-10]
i=0
for col in train_sorted.iloc[:, :-10].columns:
    #if col != train['attack_cat'].unique().any():
    if col == train['attack_cat'].unique().any():
        #print(col)
        i += 1
print(i)

In [296]:
def SaveDataFrames(DataFrame, DataFrameType, version):
    DataFrame.to_csv(str(version)+ '_'+ DataFrameType+ '.csv',index=False)
    print('saved')
    
def SaveArray(X, y, ArrayType):
    X_name = 'X_' + ArrayType + '.npy'
    np.save(X_name, X)
    y_name = 'y_' + ArrayType + '.npy'
    np.save(y_name, y)

In [291]:
SaveArray(X_train, y_train, 'train')
SaveArray(X_test, y_test, 'test')

In [297]:
SaveDataFrames(train_sorted, 'train', 1)
SaveDataFrames(test_sorted, 'test', 1)

saved
saved

In [298]:
train_sorted

,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,dload,...,Analysis,Backdoor,DoS,Exploits,Fuzzers,Generic,Normal,Reconnaissance,Shellcode,Worms
0,1.833334e-07,0.000094,0.000000,0.000033,0.000000,0.090909,0.996078,0.000000,0.034238,0.000000,...,0,0,0,0,0,0,1,0,0,0
1,1.333334e-07,0.000094,0.000000,0.000121,0.000000,0.125000,0.996078,0.000000,0.167236,0.000000,...,0,0,0,0,0,0,1,0,0,0
2,8.333335e-08,0.000094,0.000000,0.000073,0.000000,0.200000,0.996078,0.000000,0.162187,0.000000,...,0,0,0,0,0,0,1,0,0,0
3,1.000000e-07,0.000094,0.000000,0.000061,0.000000,0.166667,0.996078,0.000000,0.113895,0.000000,...,0,0,0,0,0,0,1,0,0,0
4,1.666667e-07,0.000094,0.000000,0.000146,0.000000,0.100000,0.996078,0.000000,0.161427,0.000000,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82327,8.333335e-08,0.000094,0.000000,0.000006,0.000000,0.200000,0.996078,0.000000,0.015793,0.000000,...,0,0,0,0,0,0,1,0,0,0
82328,1.843502e-02,0.001785,0.000726,0.001257,0.000024,0.000024,0.996078,0.996047,0.000024,0.000108,...,0,0,0,0,0,0,1,0,0,0
82329,0.000000e+00,0.000000,0.000000,0.000002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,1,0,0,0
82330,0.000000e+00,0.000000,0.000000,0.000002,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,1,0,0,0
82331,1.500000e-07,0.000094,0.000000,0.000006,0.000000,0.111111,0.996078,0.000000,0.008774,0.000000,...,0,0,0,0,0,0,1,0,0,0

In [299]:
test_sorted

,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,dload,...,Analysis,Backdoor,DoS,Exploits,Fuzzers,Generic,Normal,Reconnaissance,Shellcode,Worms
0,2.024634e-03,0.000470,0.000363,0.000016,0.000012,0.000074,0.988235,1.003953,2.687726e-06,0.000408,...,0,0,0,0,0,0,1,0,0,0
1,1.083170e-02,0.001221,0.003449,0.000049,0.002866,0.000078,0.243137,0.996047,1.593605e-06,0.024186,...,0,0,0,0,0,0,1,0,0,0
2,2.705215e-02,0.000658,0.001452,0.000024,0.000900,0.000014,0.243137,0.996047,2.984571e-07,0.002926,...,0,0,0,0,0,0,1,0,0,0
3,2.802737e-02,0.001033,0.001089,0.000042,0.000053,0.000014,0.243137,0.996047,5.201554e-07,0.000161,...,0,0,0,0,0,0,1,0,0,0
4,7.490901e-03,0.000845,0.000545,0.000036,0.000018,0.000033,0.996078,0.996047,1.625190e-06,0.000191,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175336,1.500000e-07,0.000094,0.000000,0.000006,0.000000,0.111111,0.996078,0.000000,9.617817e-03,0.000000,...,0,0,0,0,0,1,0,0,0,0
175337,8.429368e-03,0.000845,0.000726,0.000042,0.000024,0.000034,0.996078,0.996047,1.675453e-06,0.000236,...,0,0,0,0,0,0,0,0,1,0
175338,1.500000e-07,0.000094,0.000000,0.000006,0.000000,0.111111,0.996078,0.000000,9.617817e-03,0.000000,...,0,0,0,0,0,1,0,0,0,0
175339,1.500000e-07,0.000094,0.000000,0.000006,0.000000,0.111111,0.996078,0.000000,9.617817e-03,0.000000,...,0,0,0,0,0,1,0,0,0,0
175340,1.500000e-07,0.000094,0.000000,0.000006,0.000000,0.111111,0.996078,0.000000,9.617817e-03,0.000000,...,0,0,0,0,0,1,0,0,0,0